#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: configure
# autospec version: v2
# autospec commit: e661f3a
#
Name     : socat
Version  : 1.8.0.0
Release  : 19
URL      : http://www.dest-unreach.org/socat/download/socat-1.8.0.0.tar.gz
Source0  : http://www.dest-unreach.org/socat/download/socat-1.8.0.0.tar.gz
Summary  : socat - multipurpose relay
Group    : Development/Tools
License  : GPL-2.0 OpenSSL
Requires: socat-bin = %{version}-%{release}
Requires: socat-license = %{version}-%{release}
Requires: socat-man = %{version}-%{release}
BuildRequires : buildreq-configure
BuildRequires : libgcrypt-dev
BuildRequires : openssl-dev
BuildRequires : readline-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}
Patch1: 0001-Adding-stddef-to-nestlex.c.patch

%description
socat is a relay for bidirectional data transfer between two independent data
channels. Each of these data channels may be a file, pipe, device (terminal or
modem etc.), socket (UNIX, IP4, IP6 - raw, UDP, TCP), a file descriptor (stdin
etc.), a program, or an arbitrary combination of two of these.

%package bin
Summary: bin components for the socat package.
Group: Binaries
Requires: socat-license = %{version}-%{release}

%description bin
bin components for the socat package.


%package license
Summary: license components for the socat package.
Group: Default

%description license
license components for the socat package.


%package man
Summary: man components for the socat package.
Group: Default

%description man
man components for the socat package.


%prep
%setup -q -n socat-1.8.0.0
cd %{_builddir}/socat-1.8.0.0
%patch -P 1 -p1
pushd ..
cp -a socat-1.8.0.0 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1699922971
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
%configure --disable-static --enable-creat \
--enable-exec \
--enable-fdnum \
--enable-filan \
--enable-file \
--enable-fips \
--enable-gopen \
--enable-help \
--enable-ip4 \
--enable-ip6 \
--enable-libwrap \
--enable-listen \
--enable-openssl \
--enable-pipe \
--enable-proxy \
--enable-pty \
--enable-rawip \
--enable-readline \
--enable-retry \
--enable-stdio \
--enable-sycls \
--enable-system \
--enable-tcp \
--enable-termios \
--enable-udp \
--enable-unix
make  %{?_smp_mflags}

unset PKG_CONFIG_PATH
pushd ../buildavx2/
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -m64 -march=x86-64-v3 "
LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
%configure --disable-static --enable-creat \
--enable-exec \
--enable-fdnum \
--enable-filan \
--enable-file \
--enable-fips \
--enable-gopen \
--enable-help \
--enable-ip4 \
--enable-ip6 \
--enable-libwrap \
--enable-listen \
--enable-openssl \
--enable-pipe \
--enable-proxy \
--enable-pty \
--enable-rawip \
--enable-readline \
--enable-retry \
--enable-stdio \
--enable-sycls \
--enable-system \
--enable-tcp \
--enable-termios \
--enable-udp \
--enable-unix
make  %{?_smp_mflags}
popd
%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1699922971
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/socat
cp %{_builddir}/socat-%{version}/COPYING %{buildroot}/usr/share/package-licenses/socat/4cc77b90af91e615a64ae04893fdffa7939db84c || :
cp %{_builddir}/socat-%{version}/COPYING.OpenSSL %{buildroot}/usr/share/package-licenses/socat/82fcde476cb04d2b68f9a47c5c64f00019f6d821 || :
pushd ../buildavx2/
%make_install_v3
popd
%make_install
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/V3/usr/bin/filan
/V3/usr/bin/procan
/V3/usr/bin/socat1
/usr/bin/filan
/usr/bin/procan
/usr/bin/socat
/usr/bin/socat-broker.sh
/usr/bin/socat-chain.sh
/usr/bin/socat-mux.sh
/usr/bin/socat1

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/socat/4cc77b90af91e615a64ae04893fdffa7939db84c
/usr/share/package-licenses/socat/82fcde476cb04d2b68f9a47c5c64f00019f6d821

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/socat.1
/usr/share/man/man1/socat1.1
