#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : socat
Version  : 1.7.4.2
Release  : 15
URL      : http://www.dest-unreach.org/socat/download/socat-1.7.4.2.tar.gz
Source0  : http://www.dest-unreach.org/socat/download/socat-1.7.4.2.tar.gz
Summary  : socat - multipurpose relay
Group    : Development/Tools
License  : GPL-2.0 OpenSSL
Requires: socat-bin = %{version}-%{release}
Requires: socat-license = %{version}-%{release}
Requires: socat-man = %{version}-%{release}
BuildRequires : libgcrypt-dev
BuildRequires : openssl-dev
BuildRequires : readline-dev
Patch1: 0001-Adding-stddef-to-nestlex.c.patch

%description
socat is a relay for bidirectional data transfer between two independent data
channels. Each of these data channels may be a file, pipe, device (terminal or
modem etc.), socket (UNIX, IP4, IP6 - raw, UDP, TCP), a file descriptor (stdin
etc.), a program, or an arbitrary combination of two of these.

%package bin
Summary: bin components for the socat package.
Group: Binaries
Requires: socat-license = %{version}-%{release}

%description bin
bin components for the socat package.


%package license
Summary: license components for the socat package.
Group: Default

%description license
license components for the socat package.


%package man
Summary: man components for the socat package.
Group: Default

%description man
man components for the socat package.


%prep
%setup -q -n socat-1.7.4.2
cd %{_builddir}/socat-1.7.4.2
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1636486554
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
%configure --disable-static --enable-creat \
--enable-exec \
--enable-fdnum \
--enable-filan \
--enable-file \
--enable-fips \
--enable-gopen \
--enable-help \
--enable-ip4 \
--enable-ip6 \
--enable-libwrap \
--enable-listen \
--enable-openssl \
--enable-pipe \
--enable-proxy \
--enable-pty \
--enable-rawip \
--enable-readline \
--enable-retry \
--enable-stdio \
--enable-sycls \
--enable-system \
--enable-tcp \
--enable-termios \
--enable-udp \
--enable-unix
make  %{?_smp_mflags}

%install
export SOURCE_DATE_EPOCH=1636486554
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/socat
cp %{_builddir}/socat-1.7.4.2/COPYING %{buildroot}/usr/share/package-licenses/socat/4cc77b90af91e615a64ae04893fdffa7939db84c
cp %{_builddir}/socat-1.7.4.2/COPYING.OpenSSL %{buildroot}/usr/share/package-licenses/socat/82fcde476cb04d2b68f9a47c5c64f00019f6d821
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/filan
/usr/bin/procan
/usr/bin/socat

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/socat/4cc77b90af91e615a64ae04893fdffa7939db84c
/usr/share/package-licenses/socat/82fcde476cb04d2b68f9a47c5c64f00019f6d821

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/socat.1
